[package]
name = "bevy_fft"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_app = "0.15.0"
bevy_asset = "0.15.0"
bevy_ecs = "0.15.0"
bevy_image = "0.15.0"
bevy_math = "0.15.0"
bevy_reflect = "0.15.0"
bevy_render = "0.15.0"
bevy_utils = "0.15.0"
encase = "0.10.0"
gigs = "0.1.1"
half = "2.4.1"
